path_v1: "diff-jjoules/src/test/resources/diff-jjoules-toy-java-project"
path_v2: "diff-jjoules/src/test/resources/diff-jjoules-toy-java-project-v2"
path_output_dir: "diff-jjoules/output_example"
src_folder: "src/main/java"

time_to_wait_in_millis: 3000
iteration_warmup: 1
iteration_run: 10

coverage_cmd: "java -jar diff-jjoules/target/diff-jjoules-1.1.0-jar-with-dependencies.jar --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --task TEST_COVERAGE --output-path {{ output_path }}"
instrumentation_cmd: "java -jar diff-jjoules/target/diff-jjoules-1.1.0-jar-with-dependencies.jar --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --task TEST_INSTRUMENTATION --tests-set {{ tests_set_path }}"
execution_cmd: "java -jar diff-jjoules/target/diff-jjoules-1.1.0-jar-with-dependencies.jar --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --task TEST_EXECUTION --tests-set {{ tests_set_path }}"

indicator_to_consider_for_marking: "RAPL_ENERGY_PKG"