path_v1: "diff-jsjoules/test_resources/diff-jsjoules-toy-nodejs-project"
path_v2: "diff-jsjoules/test_resources/diff-jsjoules-toy-nodejs-project-v2"
path_output_dir: "diff-jsjoules/output_example"
src_folder: "src"

time_to_wait_in_millis: 3000
iteration_warmup: 1
iteration_run: 10

coverage_cmd: "node diff-jsjoules/src/diff-jsjoules.js coverage --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --output-path {{ output_path }} --path-diff-file {{ path_diff_file }}"
instrumentation_cmd: "node diff-jsjoules/src/diff-jsjoules.js instrumentation --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --tests {{ tests_set_path }}"
execution_cmd: "node diff-jsjoules/src/diff-jsjoules.js execution --path-to-project-v1 {{ path_project_v1 }} --path-to-project-v2 {{ path_project_v2 }} --tests {{ tests_set_path }}"

indicator_to_consider_for_marking: "RAPL_ENERGY_PKG"