name: JSJoules CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Install jscodeshift
        run: sudo npm install jscodeshift --global
      - name: Install
        run: npm install --prefix diff-jsjoules
      - name: Run tests
        run: npm run test --prefix diff-jsjoules