name: RSJoules CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.0
    - name: Build
      run: cd diff-rsjoules && cargo rustc -- -D warnings --verbose
    - name: Run tests
      run: cd diff-rsjoules && cargo test --verbose